package com.vpt.pw.demo.dtos.crf3bDTO;


import com.vpt.pw.demo.dtos.PregnantWomanDTO;
import com.vpt.pw.demo.dtos.StudiesDTO;
import com.vpt.pw.demo.dtos.TeamDTO;

public class FormCrf3bDTO {
    private Integer id;
    private PregnantWomanDTO pregnantWomanDTO;
    private StudiesDTO studiesDTO;
    private TeamDTO teamDTO;
    private String q02;
    private String q03;
    private String q13a;
    private String q13b;
    private String q13c;
    private String q13d;
    private String q13e;
    private String q13f;
    private String q13g;
    private String q13h;
    private String q13i;
    private String q13j;
    private String q13k;
    private String q13l;
    private String q13m;
    private String q13n;
    private String q13o;
    private String q14;
    private String q15a;
    private String q15b;
    private String q15c;
    private String q15d;
    private String q15e;
    private String q15f;
    private String q15g;
    private String q15h;
    private String q15i;
    private String q15j;
    private String q15k;
    private String q15l;
    private String q15m;
    private String q15n;
    private String q15o;
    private String q15p;
    private String q15q;
    private String q15r;
    private String q16;
    private String q17;
    private String q19;
    private String q20;
    private String q21;
    private String q22;
    private String q23;
    private String q24;
    private String q25;
    private String q26;
    private String q27;
    private String q28;
    private String q29;
    private String q30;
    private String q31;
    private String q32;
    private String q33;
    private String q34;
    private String q35;
    private String q36;
    private String q37;
    private String q38;
    private String q39;
    private String q40;
    private String q41;
    private String q42;
    private String q43a;
    private String q43b;
    private String q43c;
    private String q43d;
    private String q43e;
    private String q43f;
    private String q43g;
    private String q43h;
    private String q43i;
    private String q43j;
    private String q43k;
    private String q44;
    private String q45;
    private String q46;
    private String q47;
    private String q48;
    private String q49;
    private String q50;
    private String q51;
    private String q52;
    private String q53;
    private String q54;
    private String q55;
    private String q56;
    private String q57;
    private String q58;
    private String q59;
    private String q60;


}
